#define Svorak_A (Key) { HID_KEYBOARD_A_AND_A, KEY_FLAGS }
#define Svorak_B (Key) { HID_KEYBOARD_N_AND_N, KEY_FLAGS }
#define Svorak_C (Key) { HID_KEYBOARD_I_AND_I, KEY_FLAGS }
#define Svorak_D (Key) { HID_KEYBOARD_H_AND_H, KEY_FLAGS }
#define Svorak_E (Key) { HID_KEYBOARD_D_AND_D, KEY_FLAGS }
#define Svorak_F (Key) { HID_KEYBOARD_Y_AND_Y, KEY_FLAGS }
#define Svorak_G (Key) { HID_KEYBOARD_U_AND_U, KEY_FLAGS }
#define Svorak_H (Key) { HID_KEYBOARD_J_AND_J, KEY_FLAGS }
#define Svorak_I (Key) { HID_KEYBOARD_G_AND_G, KEY_FLAGS }
#define Svorak_J (Key) { HID_KEYBOARD_C_AND_C, KEY_FLAGS }
#define Svorak_K (Key) { HID_KEYBOARD_V_AND_V, KEY_FLAGS }
#define Svorak_L (Key) { HID_KEYBOARD_P_AND_P, KEY_FLAGS }
#define Svorak_M (Key) { HID_KEYBOARD_M_AND_M, KEY_FLAGS }
#define Svorak_N (Key) { HID_KEYBOARD_L_AND_L, KEY_FLAGS }
#define Svorak_O (Key) { HID_KEYBOARD_S_AND_S, KEY_FLAGS }
#define Svorak_P (Key) { HID_KEYBOARD_R_AND_R, KEY_FLAGS }
#define Svorak_Q (Key) { HID_KEYBOARD_X_AND_X, KEY_FLAGS }
#define Svorak_R (Key) { HID_KEYBOARD_O_AND_O, KEY_FLAGS }
#define Svorak_S (Key) { HID_KEYBOARD_SEMICOLON_AND_COLON, KEY_FLAGS }
#define Svorak_T (Key) { HID_KEYBOARD_K_AND_K, KEY_FLAGS }
#define Svorak_U (Key) { HID_KEYBOARD_F_AND_F, KEY_FLAGS }
#define Svorak_V (Key) { HID_KEYBOARD_PERIOD_AND_GREATER_THAN , KEY_FLAGS }
#define Svorak_W (Key) { HID_KEYBOARD_COMMA_AND_LESS_THAN, KEY_FLAGS }
#define Svorak_X (Key) { HID_KEYBOARD_B_AND_B, KEY_FLAGS }
#define Svorak_Y (Key) { HID_KEYBOARD_T_AND_T, KEY_FLAGS }
#define Svorak_Z (Key) { HID_KEYBOARD_SLASH_AND_QUESTION_MARK, KEY_FLAGS }
#define Svorak_AO (Key) { HID_KEYBOARD_Q_AND_Q, KEY_FLAGS }
#define Svorak_AE (Key) { HID_KEYBOARD_W_AND_W, KEY_FLAGS }
#define Svorak_OE (Key) { HID_KEYBOARD_E_AND_E, KEY_FLAGS }
#define Svorak_1 (Key) { HID_KEYBOARD_1_AND_EXCLAMATION_POINT, KEY_FLAGS }
#define Svorak_2 (Key) { HID_KEYBOARD_2_AND_AT, KEY_FLAGS }
#define Svorak_3 (Key) { HID_KEYBOARD_3_AND_POUND, KEY_FLAGS }
#define Svorak_4 (Key) { HID_KEYBOARD_4_AND_DOLLAR, KEY_FLAGS }
#define Svorak_5 (Key) { HID_KEYBOARD_5_AND_PERCENT, KEY_FLAGS }
#define Svorak_6 (Key) { HID_KEYBOARD_6_AND_CARAT, KEY_FLAGS }
#define Svorak_7 (Key) { HID_KEYBOARD_7_AND_AMPERSAND, KEY_FLAGS }
#define Svorak_8 (Key) { HID_KEYBOARD_8_AND_ASTERISK, KEY_FLAGS }
#define Svorak_9 (Key) { HID_KEYBOARD_9_AND_LEFT_PAREN, KEY_FLAGS }
#define Svorak_0 (Key) { HID_KEYBOARD_0_AND_RIGHT_PAREN, KEY_FLAGS }

#define Svorak_Enter (Key) { HID_KEYBOARD_ENTER, KEY_FLAGS }
#define Svorak_Escape (Key) { HID_KEYBOARD_ESCAPE, KEY_FLAGS }
#define Svorak_Backspace (Key) { HID_KEYBOARD_DELETE, KEY_FLAGS }
#define Svorak_Tab (Key) { HID_KEYBOARD_TAB, KEY_FLAGS }
#define Svorak_Spacebar (Key) { HID_KEYBOARD_SPACEBAR, KEY_FLAGS }
#define Svorak_Plus (Key) { HID_KEYBOARD_MINUS_AND_UNDERSCORE, KEY_FLAGS }
#define Svorak_Backtick (Key) { HID_KEYBOARD_EQUALS_AND_PLUS, KEY_FLAGS }
#define Svorak_Quote (Key) { HID_KEYBOARD_BACKSLASH_AND_PIPE, KEY_FLAGS }
#define Svorak_Minus (Key) { HID_KEYBOARD_QUOTE_AND_DOUBLEQUOTE, KEY_FLAGS }
#define Svorak_Paragraph (Key) { HID_KEYBOARD_GRAVE_ACCENT_AND_TILDE, KEY_FLAGS }
#define Svorak_Comma (Key) { HID_KEYBOARD_LEFT_BRACKET_AND_LEFT_CURLY_BRACE, KEY_FLAGS }
#define Svorak_Caret (Key) { HID_KEYBOARD_RIGHT_BRACKET_AND_RIGHT_CURLY_BRACE, KEY_FLAGS }
#define Svorak_Period (Key) { HID_KEYBOARD_Z_AND_Z, KEY_FLAGS }
#define Svorak_LessThan (Key) { HID_KEYBOARD_NON_US_BACKSLASH_AND_PIPE, KEY_FLAGS }

#define Svorak_LeftAlt (Key) { HID_KEYBOARD_LEFT_ALT, KEY_FLAGS }
#define Svorak_LeftControl (Key) { HID_KEYBOARD_LEFT_CONTROL, KEY_FLAGS }
#define Svorak_LeftGui (Key) { HID_KEYBOARD_LEFT_GUI, KEY_FLAGS }
#define Svorak_LeftShift (Key) { HID_KEYBOARD_LEFT_SHIFT, KEY_FLAGS }
#define Svorak_RightAltGr (Key) { HID_KEYBOARD_RIGHT_ALT, KEY_FLAGS }
#define Svorak_RightControl (Key) { HID_KEYBOARD_RIGHT_CONTROL, KEY_FLAGS }
#define Svorak_RightGui (Key) { HID_KEYBOARD_RIGHT_GUI, KEY_FLAGS }
#define Svorak_RightShift (Key) { HID_KEYBOARD_RIGHT_SHIFT, KEY_FLAGS }
